import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SWRProvider from "@/components/SWRProvider";
import RewardProvider from "@/components/RewardProvider";
import { UnifiedDataProvider } from "@/components/UnifiedDataProvider";
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createServerComponentClient({
    cookies: () => cookieStore,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SWRProvider>
          <RewardProvider>
            {session ? (
              <UnifiedDataProvider>
                <Navbar />
                {children}
              </UnifiedDataProvider>
            ) : (
              <>
                <Navbar />
                {children}
              </>
            )}
            <Toaster 
              position="bottom-center" 
              theme="dark"
              toastOptions={{
                style: {
                  background: 'rgb(30 41 59)', // slate-800
                  border: '1px solid rgb(51 65 85)', // slate-700
                  color: 'rgb(226 232 240)', // slate-200
                },
                className: 'font-medium',
              }}
              closeButton 
            />
          </RewardProvider>
        </SWRProvider>
      </body>
    </html>
  );
}
