import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SWRProvider from "@/components/SWRProvider";
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import PlayerStatsBar from "@/components/PlayerStatsBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createServerComponentClient({
    cookies: () => cookieStore,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SWRProvider>
          <Navbar />
          {children}
        </SWRProvider>
      </body>
    </html>
  );
}
